### ISSUE TITLE
Yes is not defined

### ISSUE THREAD

**Issue by Splizard** [armandg/sol3rd#4]
```
 [✔] Getting available versions                    
 [✔] Getting installed versions                        

Upgrading google-chrome-stable
Installed: 64.0.3282.167
Available: 69.0.3497.100
OK? (yes or no): yes
Traceback (most recent call last):
  File "/usr/bin/sol3rd", line 11, in <module>
    load_entry_point('sol3rd==0.1', 'console_scripts', 'sol3rd')()
  File "/usr/lib/python2.7/site-packages/sol3rd/sol3rd.py", line 202, in main
    apps_upgradeable = get_upgradeable()
  File "/usr/lib/python2.7/site-packages/sol3rd/sol3rd.py", line 138, in get_upgradeable
    do_upgrade = input('\nOK? (yes or no): ')
  File "<string>", line 1, in <module>
NameError: name 'yes' is not defined
```

**Comment by geirawsm** [comment]
Script is written for Python3, has not been tested with Python2 (which gives this error).
Added requirement in readme for now (0b71fec909fdc846fb12879108dd5b7cb2d91e53)

Will look into the code to see if this is fixable. Solution as of now is to install Python3.

**Comment by Splizard** [comment]
Thanks for the response, I have both python3 and python2 installed on Solus. 
By default, pip and python commands are pointing to python2.
Using pip3 to install Sol3rd solved the issue.

**Comment by geirawsm** [comment]
Great to hear, hope it keeps working and please hit me with more issues when they come.
