### ISSUE TITLE
List 3rd party packages

### ISSUE THREAD

**Issue by Splizard** [armandg/sol3rd#5]
I would like to be able to list 3rd party packages.
Perhaps sol3rd -l, --list

**Comment by geirawsm** [comment]
So just a plain print of the packages with description, or just the names?

**Comment by Splizard** [comment]
Yea, the use case here is that I am vaguely aware of what packages are available but not all of them (without checking what is available using the software center). 

So I think simply printing the names of the packages is sufficient.

**Comment by geirawsm** [comment]
Allright, I'll add it to the next release.

**Comment by geirawsm** [comment]
Updated in db780e6624a7e1e4da279b1c2d27733cb9dd7c36.
@Splizard, would you mind grabbing the new script raw and testing it to see if it works like intended before I push to pypi?

**Comment by geirawsm** [comment]
Ok, I'm gonna go ahead and add this anyways.
